# Generated by Django 5.0.6 on 2024-06-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_banner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
